<?xml version="1.0" encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href="htmlplot.xsl"?>

<!DOCTYPE plotscript [
	<!ELEMENT plotscript (section+)>
	<!ATTLIST plotscript lastmodified CDATA "the dawn of time">
	<!ATTLIST plotscript show-alias CDATA "yes">
	<!ELEMENT section (description?,command*)>
	<!ATTLIST section title CDATA #REQUIRED>
	<!ELEMENT command ((cannon,shortname,description,example*,seealso?) |
					   (alias,shortname))>
	<!ATTLIST command id ID #REQUIRED
			          created CDATA #IMPLIED>
  	<!ELEMENT cannon      (#PCDATA)>
  	<!ELEMENT shortname   (#PCDATA)>
  	<!ELEMENT description ANY>
  	<!ELEMENT example     (#PCDATA)>
  	<!ATTLIST example c IDREF #IMPLIED>
  	<!ELEMENT alias       (#PCDATA)>
  	<!ELEMENT seealso (ref+)>

  	<!ELEMENT ref         (#PCDATA)>
  	<!ELEMENT lb		  (#PCDATA)>
  	<!ELEMENT param		  (#PCDATA)>
]>
<!--

DOCUMENTATION FOR THIS XML FILE:

This markup (hereby refered to as PDL (Plotscript Dictionary Language)) is
designed to reduce the time spent maintaining the Plotscripting Dictionary, and
to enable easier porting to other formats.

The root element is the <plotscript> element. It has a lastmodified attribute,
which is the text date that the file was last modified. Update this when you
make a change.

In <plotscript>, there is a series of <section> elements, each with a title
attribute. These are to group the plotscripting commands into logical groups,
such as <section title="Wait Commands"> or <section title="Math Operators">

The heart of the PDL are the <command> elements inside the <section>s. It has a
single attribute, id. This is essentially the whitespace stripped version of the
command (the "wait for text box" command would have an id of "waitfortextbox").
This is used to uniquely identify each command. It's used in many ways, from
crosslinking command entries to generating a file for HssEd to use.

Inside the <command> element are either two or four+ elements, in this order:
Case 1: Full command definition
  <cannon> - This is the "cannonical" form of the command: the fully spaced
  			 command with parameter prototypes. Example: move hero to x (who, x)
  <shortname> - This is the short version of the command, used for crosslinking,
  				indexes, etc. It is the <cannon> element, minus the parameters.
  				Example: move hero to x
  <description> - This is a paragraph (or more) of text describing what the
  				  command does, and how to use it. Use <lb/> to put paragraphs
  				  in, and <p></p> when refering to a parameter (to avoid user
  				  confusion) No HTML is allowed (at this time) Example: Well, it
  				  would be pretty long...
  <example>* - Finally, most commands should have some sort of example on how to
  			   use the command. It will be displayed in a mono-space font, so
  			   it's easy to Plotscript. But, be sure to format it properly:
			   Example:
			   <example># first example line has no line-break
# the second (and more) lines should have no indentation
# and so forth</example>

Case 2: Alias command definition
  <alias> - If a command is an alias to another command (or is so closely
  			related that they're in the same entry, use the <alias> element. Put
  			the ID of the real command in here. Example: begin
  <shortname> - Aliases also need a short name, since they are technically
  				different from their alias. Example: end

Basically, you should be able to examine the entries that already exist. It's
fairly self evident what everything does.

These are cut-and-paste copies of <command> elements, so you don't have to type
everything out 10000000000 times. They are also indented properly for this file.

#===== Full description

		<command id="">
			<cannon></cannon>
			<shortname></shortname>
			<description></description>
			<example></example>
		</command>

#===== Full description with borrowed example

		<command id="">
			<cannon></cannon>
			<shortname></shortname>
			<description></description>
			<example c="">
		</command>

#===== Alias

		<command id="">
			<alias></alias>
			<shortname></shortname>
		</command>


#=====

Which reminds me: Indentation. For each "level" you go down in the heirarchy,
you indent once. Many code specific editors will maintain this indentation level
for until you explicitly change it, so it isn't difficult. Notepad users will
have to do it manually, but you MUST do it. Remember: 1 indent = 1 tab.

"Mono means 'one'. Rail means 'rail'. And that concludes our training."
	~ Monorail guy, Simpsons

-->
<plotscript lastmodified="right now">
	<section title="Declarations">
		<command id="plotscript">
			<cannon>plotscript, name, argumentnames (statements)</cannon>
			<shortname>plotscript</shortname>
			<description>The plotscript command contains a list of commands that can be triggered directly by an event in your game. Plotscript starts with the keyword plotscript, a comma, and then the name of the plotscript. If there are any arguments to the script, you list their names separated by commas after the name of the script with default values. Then comes the text of the script. It is enclosed in <ref>begin</ref> and <ref>end</ref> statements. Scripts that are defined as plotscripts can be called directly from events in your game, or by name within other scripts.</description>
			<example># example of a simple script
plotscript,my first script,begin
	# commands go here
end</example>
			<example># example of a script with arguments
plotscript,my fancy script,fe=0,fi=0,fo=0,begin
	# commands go here,
	# and they can use the aruments fe, fi, and fo
	# that where passed to the script
end</example>
		</command>
		<command id="script">
			<cannon>script, name, argumentnames (statements)</cannon>
			<shortname>script</shortname>
			<description>The script command contains a list of commands. Script starts with the keyword script, a comma, and then the name of the script. If there are any arguments to the script, you list their names separated by commas after the name of the script with default values. Then comes the text of the script. It is enclosed in <ref>begin</ref> and <ref>end</ref> statements. Scripts that are defined as script cannot be called directly from events in your game. They can only be called by name within other scripts. To make a script that can be run directly from your game, use <ref>plotscript</ref>.</description>
			<example># example of a simple script
script,my first script,begin
	# commands go here
end</example>
			<example># example of a script with arguments
script,my fancy script,fe=0,fi=0,fo=0,begin
	# commands go here,
	# and they can use the aruments fe, fi, and fo
	# that where passed to the script
end</example>
		</command>
		<command id="globalvariable">
			<cannon>global variable (id,name)</cannon>
			<shortname>global variable</shortname>
			<description>Creates a global variable that can be used in any script. The first argument to the global variable declaration is a unique ID number. The second argument is the name of the variable. The ID number for a global variable is a number from 0 to 4095. Each global variable must have a unique number, but this number will not conflict with the ID numbers you use for scripts. It is all right to have a script and a global variable with the same ID number. See also <ref>variable</ref></description>
			<example># any script can read and set the value of a global
global variable(1,mini game score)</example>
		</command>
		<command id="variable">
			<cannon>variable (name)</cannon>
			<shortname>variable</shortname>
			<description>Creates a local variable that can only be used inside the script where it was created. The value of this variable is lost when the script ends. If you need a variable who&apos;s value persists between calls to a script, or that is automatically saved when the player saves their game, you will need to use a <ref>globalvariable</ref> instead.</description>
			<example>variable(points) # make a new variable
variable+=1 # add one to it</example>
		</command>
		<command id="defineconstant">
			<cannon>define constant (number,name)</cannon>
			<shortname>define constant</shortname>
			<description>Creates a global constant. The first argument is the number that the constant will represent, and the second argument is the name of the constant. Use constants to replace commonly used numbers with friendly names. The following constants have been delacred for you in PLOTSRC.HSD:<lb /><ref>zero</ref> <ref>one</ref> <ref>two</ref> <ref>three</ref> <ref>four</ref> <ref>five</ref> <ref>six</ref> <ref>seven</ref> <ref>eight</ref> <ref>nine</ref> <ref>ten</ref> <ref>false</ref> <ref>true</ref> <ref>off</ref> <ref>on</ref> <ref>north</ref> <ref>east</ref> <ref>south</ref> <ref>west</ref> <ref>up</ref> <ref>down</ref> <ref>left</ref> <ref>right</ref> <ref>upkey</ref> <ref>downkey</ref> <ref>leftkey</ref> <ref>rightkey</ref> <ref>usekey</ref> <ref>cancelkey</ref> <ref>menukey</ref> <ref>anykey</ref> <ref>me</ref> <ref>none</ref> <ref>autonumber</ref> <ref>currentstat</ref> <ref>maximumstat</ref> <ref>northwall</ref> <ref>eastwall</ref> <ref>southwall</ref> <ref>westwall</ref> <ref>vehiclea</ref> <ref>vehiclea</ref> <ref>harmtile</ref> <ref>overheadtile</ref></description>
		</command>
		<command id="include">
			<cannon>include, filename</cannon>
			<shortname>include</shortname>
			<description>The include command inserts another text file into your script. It is followed by a single filename that tells what file will be included. Windows long filenames are not supported. Every plotscript file should start with include, plotscr.hsd The PLOTSCR.HSD file contains definitions and constants for most of the other plotscripting commands.</description>
			<example>include, plotscr.hsd # Plotscripting definitions
include, mygame.hsi # constants particular to my game</example>
		</command>
		<command id="definescript">
			<cannon>define script (id,name,arguments)</cannon>
			<shortname>define script</shortname>
			<deprecated>ubersetzung</deprecated>
			<description><note>This declaration is available for backwards compatability, but it is not required anymore. See <ref>script</ref> and <ref>plotscript</ref> instead.</note> The define script command names an old-style script, and associates it with an ID number. Old scripts used to require a unique ID number. The first argument is the <p>ID number</p>. It is a number between 1 and 16383. If you try to give two individual scripts the same <p>ID number</p>, your script file will not compile. The next argument is the <p>name</p> of the script. this is the same name that will used later in your script command. The third argument is the number of arguments that the script can accept. If it doesnt need any arguments (most scripts don't) then use <ref>none</ref>. If there are arguments, you then follow the argument count with default values for each argument.</description>
			<example># example of a simple script definition
define script (1,my first script,none)</example>
			<example># example of a script definition with arguments. this script
# has three arguments, all of which default to zero if they
# are not specified
define script (2,my fancy script,3,0,0,0)</example>
		</command>
	</section>
	<section title="Wait Commands">
		<command id="wait">
			<cannon>wait (ticks)</cannon>
			<shortname>wait</shortname>
			<description>Makes the script wait for the specified number of ticks. There are roughly 18 ticks to a second, but this can vary under some conditions. If you leave out the argument, it will wait for one tick.</description>
			<example>show text box(2) # Show a text box
wait(50) # Wait about 3 seconds
advance text box # "hit spacebar"</example>
		</command>
		<command id="waitfortextbox">
			<cannon>wait for text box</cannon>
			<shortname>wait for text box</shortname>
			<description>Makes the script wait until there is no text box displaying on the screen. Useful to know when to move on after using a <ref>showtextbox</ref> command.</description>
			<example>show text box(2) # Show a text box
wait for text box # wait until the player continues</example>
		</command>
		<command id="waitformenu">
			<cannon>wait for menu (menu handle)</cannon>
			<shortname>wait for menu</shortname>
			<description>Given a <p>menu handle</p> (for example, the one returned by <ref>openmenu</ref>), causes the script to wait until that menu has been closed.</description>
		</command>
		<command id="waitforhero">
			<cannon>wait for hero (who)</cannon>
			<shortname>wait for hero</shortname>
			<description>Waits for the specified hero stop walking. Use the constant <ref>me</ref> to refer to the leader, or use numbers 0,1,2,3 to refer to a specific hero. If you leave out the argument, the first hero will be assumed.</description>
			<example>move hero to y (me, 10) # move hero to (x, 10)
wait for hero (me) # wait until he stops</example>
		</command>
		<command id="waitforkey">
			<cannon>wait for key (key)</cannon>
			<shortname>wait for key</shortname>
			<description>Waits for the player to press a key. You can use the following constants: <ref>anykey</ref>, <ref>upkey</ref>, <ref>downkey</ref>, <ref>leftkey</ref>, <ref>rightkey</ref>, <ref>usekey</ref>, <ref>cancelkey</ref>, or <ref>menukey</ref>. If you do not specify, then <ref>anykey</ref> will be used. These are not scancodes, and can not be mixed with scancodes! Use <ref>waitforscancode</ref> if you want to use scancodes or wait for other keys. <p>usekey</p> will wait for Space, Ctrl or Enter; and <p>cancelkey</p> and <p>menukey</p> both wait for Alt or Esc. If and only if anykey is used, waitforkey will return the scancode of the key that was pressed.</description>
			<example>show text box(623) # "press cancel!"
wait for key(cancel key)</example>
		</command>
		<command id="waitforscancode">
			<cannon>wait for scancode (key)</cannon>
			<shortname>wait for scancode</shortname>
			<added>ubersetzung</added>
			<description>Waits for the player to press a specific key. You can use any of the constants from <ref>keyispressed</ref> to specify the key. <note>You must <ref>include</ref> scancode.hsi to use these constants.</note></description>
			<example>show text box(624) # "press P!"
wait for scancode(key:P)</example>
		</command>
		<command id="waitfornpc">
			<cannon>wait for NPC (who)</cannon>
			<shortname>wait for NPC</shortname>
			<description>Waits for the specified NPC to stop walking. The argument is the number of the NPC, 0 to 35. If more than one copy of the NPC exists on the map, it only checks the first one.</description>
			<example>walk NPC (2,up,3) # make the NPC go up three spaces
wait for NPC (2) # wait until he&apos;s done</example>
		</command>
		<command id="waitforcamera">
			<cannon>wait for camera</cannon>
			<shortname>wait for camera</shortname>
			<description>Wait for the camera to stop panning after a <ref>pancamera</ref> or <ref>focuscamera</ref> command.</description>
			<example>pan camera (left,10) # show the villan 10 tiles off screen
wait for camera # wait until he&apos;s on screen</example>
		</command>
		<command id="waitforall">
			<cannon>wait for all</cannon>
			<shortname>wait for all</shortname>
			<description>Waits for any camera motion to stop, waits for all heroes to stop walking, and if <ref>suspendnpcs</ref> is active, waits for all NPCs to stop walking.</description>
			<example># do a bunch of things all at once
wait for all # wait until everything is done</example>
		</command>
	</section>
	<section title="Suspend and Resume">
		<command id="suspendplayer">
			<cannon>suspend player</cannon>
			<shortname>suspend player</shortname>
			<description>Blocks the player from controlling the game, so the plotscript can have exclusive control. The one exception to this is text boxes. The player can advance text boxes no matter what, unless you use <ref>suspendboxadvance</ref>.</description>
			<example>suspend player
# do stuff
resume player</example>
		</command>
		<command id="resumeplayer">
			<cannon>resume player</cannon>
			<shortname>resume player</shortname>
			<description>Restores normal control after a <ref>suspendplayer</ref> command. This is very important. If you use <ref>suspendplayer</ref>, but forget resume player, the game will be stuck after the script ends.</description>
			<example c="suspendplayer" />
		</command>
		<command id="suspendnpcs">
			<cannon>suspend NPCs</cannon>
			<shortname>suspend NPCs</shortname>
			<description>Stops NPCs from walking around automatically. When suspend NPCs is run, all NPCs stop in their tracks, ready for you to control them with the <ref>walknpc</ref> command</description>
			<example>suspend NPCs
# do stuff
resume NPCs</example>
		</command>
		<command id="resumenpcs">
			<cannon>resume NPCs</cannon>
			<shortname>resume NPCs</shortname>
			<description>Restores automatic NPC movement after a <ref>suspendnpcs</ref> command</description>
			<example c="suspendnpcs" />
		</command>
		<command id="suspendobstruction">
			<cannon>suspend obstruction</cannon>
			<shortname>suspend obstruction</shortname>
			<description>Allows heroes to walk through NPCs, allows NPCs to walk through heroes, and allows NPCs to walk through each other. Use <ref>resumeobstruction</ref> to restore normal obstruction behavior.</description>
			<example>suspend obstruction
# walk through things
resume obstruction</example>
		</command>
		<command id="resumeobstruction">
			<cannon>resume obstruction</cannon>
			<shortname>resume obstruction</shortname>
			<description>Restores normal obstruction after a <ref>suspendobstruction</ref> command</description>
			<example c="suspendobstruction" />
		</command>
		<command id="suspendherowalls">
			<cannon>suspend hero walls</cannon>
			<shortname>suspend hero walls</shortname>
			<description>Allows heroes to walk through walls. Use <ref>resumeherowalls</ref> to restore normal wall behavior.</description>
			<example>suspend hero walls # hero is now a ghost
# walk through things
resume hero walls # back to mortality...</example>
		</command>
		<command id="resumeherowalls">
			<cannon>resume hero walls</cannon>
			<shortname>resume hero walls</shortname>
			<description>Restores normal wall behavior after a <ref>suspendherowalls</ref> command</description>
			<example c="suspendherowalls" />
		</command>
		<command id="suspendnpcwalls">
			<cannon>suspend NPC walls</cannon>
			<shortname>suspend NPC walls</shortname>
			<description>Allows NPCs to walk through walls. Use <ref>resumenpcwalls</ref> to restore normal wall behavior.</description>
			<example>suspend NPC walls # npc is now a ghost
# walk through things
resume NPC walls # back to mortality...</example>
		</command>
		<command id="resumenpcwalls">
			<cannon>resume NPC walls</cannon>
			<shortname>resume NPC walls</shortname>
			<description>Restores normal wall behavior after a <ref>suspendnpcwalls</ref> command.</description>
			<example c="suspendnpcwalls" />
		</command>
		<command id="suspendcaterpillar">
			<cannon>suspend caterpillar</cannon>
			<shortname>suspend caterpillar</shortname>
			<description>Stops your other heroes from following the leader. This is useful when you want to control them individually with <ref>walkhero</ref> commands. In earlier versions this was misspelled as suspend catapillar. The old spelling still works for backwards compatability.</description>
			<example>suspend caterpillar # cutscene
# move heroes, probably fight a battle or two...
resume caterpillar # normal game again.</example>
		</command>
		<command id="resumecaterpillar">
			<cannon>resume caterpillar</cannon>
			<shortname>resume caterpillar</shortname>
			<description>Reverses the <ref>suspendcaterpillar</ref> command, and makes your other heroes follow the leader as normal. In earlier versions this was misspelled as resume catapillar. The old spelling still works for backwards compatability.</description>
			<example c="suspendcaterpillar" />
		</command>
		<command id="suspendcatapillar">
			<alias>suspendcaterpillar</alias>
			<shortname>suspend catapillar</shortname>
			<deprecated>May 22 2001</deprecated>
		</command>
		<command id="resumecatapillar">
			<alias>resumecaterpillar</alias>
			<shortname>resume catapillar</shortname>
			<deprecated>May 22 2001</deprecated>
		</command>
		<command id="suspendrandomenemies">
			<cannon>suspend random enemies</cannon>
			<shortname>suspend random enemies</shortname>
			<description>Prevents enemies from attacking your party while walking over tiles that can normally spawn random battles. This is useful to prevent battles from interrupting a plotscript. In earlier versions, this was misspelled as suspend random enemys. The old spelling still works for backwards compatability.</description>
			<example>suspend random enemies # no battles for now
walk hero (me, up, 10) # cross pit of evil monsters of doom
resume random enemies # back to normal</example>
		</command>
		<command id="resumerandomenemies">
			<cannon>resume random enemies</cannon>
			<shortname>resume random enemies</shortname>
			<description>Undoes the <ref>suspendrandomenemies</ref> command and allows random battles to occur as normal. In earlier versions, this was misspelled as resume random enemys. The old spelling still works for backwards compatability.</description>
			<example c="suspendrandomenemies" />
		</command>
		<command id="suspendrandomenemys">
			<alias>suspendrandomenemies</alias>
			<shortname>suspend random enemys</shortname>
		</command>
		<command id="resumerandomenemys">
			<alias>resumerandomenemies</alias>
			<shortname>resume random enemys</shortname>
		</command>
		<command id="suspendboxadvance">
			<cannon>suspend box advance</cannon>
			<shortname>suspend box advance</shortname>
			<description>Prevents the player from advancing or clearing text boxes by pressing keys. While this is active, the only way to make a text box advance is with the <ref>advancetextbox</ref> command (or <ref>showtextbox</ref>). Useful for cut scenes that play out like a movie, where the player just watches the dialogue unfold. Be very careful with this command, since you do not want to leave the player stuck on a text box forever.</description>
			<example>suspend box advance # stop players from mucking things up
show text box(2) # Show a text box
wait(45) # Wait about 3 seconds
advance text box # "hit spacebar"
resume box advance # go back to normal</example>
		</command>
		<command id="resumeboxadvance">
			<cannon>resume box advance</cannon>
			<shortname>resume box advance</shortname>
			<description>Undoes the <ref>suspendboxadvance</ref> command and allows the player to advance and clear text boxes by pressing keys as normal.</description>
			<example c="suspendboxadvance" />
		</command>
		<command id="suspendoverlay">
			<cannon>suspend overlay</cannon>
			<shortname>suspend overlay</shortname>
			<description>Draws old-style overhead tiles under heroes and NPCs instead of over them. This does not affect the drawing of normal layers. You might still find this useful for creating bridges or catwalks that can be walked on or passed under. Undo with <ref>resumeoverlay</ref>.</description>
		</command>
		<command id="resumeoverlay">
			<cannon>resume overlay</cannon>
			<shortname>resume overlay</shortname>
			<description>Undoes the <ref>suspendoverlay</ref> command, causing overhead tiles to be drawn over heroes and NPCs as normal.</description>
		</command>
		<command id="suspendmapmusic">
			<cannon>suspend map music</cannon>
			<shortname>suspend map music</shortname>
			<added>serendipity</added>
			<description>Causes ambient music not to automatically play when you enter a map. Does not affect the currently playing music, or the map's ambient music. Use when playing thematic music during a scene that involves changing maps.</description>
			<example># begin scene
play song(song:Happy Times)
show textbox (117)
wait for textbox
# goto another map without triggering music
fade screen out
wait
suspend map music
use door(3)
fade screen in
# continue scene
show textbox (118)
wait for textbox
# return to normal music behaviour and play the ambient music
resume map music
play song (get ambient music)</example>
		<seealso><ref>setambientmusic</ref> <ref>getambientmusic</ref></seealso>
		</command>
		<command id="resumemapmusic">
			<cannon>resume map music</cannon>
			<shortname>resume map music</shortname>
			<added>serendipity</added>
			<description>Causes ambient music to automatically start playing when you enter a map again after a <ref>suspendmapmusic</ref> command.</description>
		</command>
	</section>
	<section title="Moving Heroes">
		<command id="walkhero">
			<cannon>walk hero (who, direction, distance)</cannon>
			<shortname>walk hero</shortname>
			<description>Makes the specified hero move in the specified direction for the specified number of tiles. The first argument tells who to move. Use <ref>me</ref> or numbers 0-3. The second argument is the direction. Use the constants: <ref>north</ref>, <ref>south</ref>, <ref>east</ref>, <ref>west</ref>, <ref>up</ref>, <ref>down</ref>, <ref>left</ref>, or <ref>right</ref>. The third argument is the number of tiles to move. If you leave out the third argument, the hero will move one tile. Walk hero is usually used with the <ref>waitforhero</ref> command. You should normally use the <ref>suspendplayer</ref> command before moving heroes, and if you want to move heroes other than the leader, you should use the <ref>suspendcaterpillar</ref> command.</description>
			<example>suspend player # stop player
walk hero(me,up,3) # move him up 3 tiles
resume player # ok, done</example>
		</command>
		<command id="setherodirection">
			<cannon>set hero direction (who, direction)</cannon>
			<shortname>set hero direction</shortname>
			<description>Makes the specified hero face in the specified direction. The following constants are avaialable for direction: <ref>north</ref>, <ref>south</ref>, <ref>east</ref>, <ref>west</ref>, <ref>up</ref>, <ref>down</ref>, <ref>left</ref>, or <ref>right</ref>.</description>
			<example>set hero direction (me,right) # face right</example>
		</command>
		<command id="setheroframe">
			<cannon>set hero frame (who, frame)</cannon>
			<shortname>set hero frame</shortname>
			<description>Sets the walking frame of the specified hero to 0 or 1.</description>
			<seealso>
				<ref>heroframe</ref>
			</seealso>
		</command>
		<command id="setheroposition">
			<cannon>set hero position (who, x, y)</cannon>
			<shortname>set hero position</shortname>
			<description>Instantly moves the specified hero to an X,Y position on the map. The coordinates are in units of tiles. For pixel-positioning use the <ref>puthero</ref> command.</description>
		</command>
		<command id="setheroz">
			<cannon>set hero z (who, z)</cannon>
			<shortname>set hero z</shortname>
			<description>Sets the Z location of the specified hero. The Z location is the number of pixels above the tile they are standing on. Useful for scripts where you want a hero to jump or levitate.</description>
		</command>
		<command id="walkherotox">
			<cannon>walk hero to x (who,x)</cannon>
			<shortname>walk hero to x</shortname>
			<description>Makes the specified hero walk to a given X coordinate on the map</description>
		</command>
		<command id="walkherotoy">
			<cannon>walk hero to y (who,x)</cannon>
			<shortname>walk hero to y</shortname>
			<description>Makes the specified hero walk to a given Y coordinate on the map</description>
		</command>
		<command id="checkherowall">
			<cannon>check hero wall (who,direction)</cannon>
			<shortname>check hero wall</shortname>
			<description>Returns true if there is a wall blocking the hero from moving in the specified direction. No actual movement takes place.</description>
		</command>
		<command id="setherospeed">
			<cannon>set hero speed (who, speed)</cannon>
			<shortname>set hero speed</shortname>
			<description>Changes the walking speed of the specified hero. If you do not specify a speed, the hero&apos;s speed will return to the default, 4. Be careful with using speeds that do not divide evenly into 20, because tiles are 20 pixels in size, and an irregular walking speed may cause your hero to become misaligned with the tiles.</description>
			<seealso>
				<ref>getherospeed</ref>
			</seealso>
		</command>
		<command id="usedoor">
			<cannon>use door (number)</cannon>
			<shortname>use door</shortname>
			<description>Instantly uses the numbered door, just as if you had stepped into it. (This command implies a one-tick <ref>wait</ref>)</description>
		</command>
		<command id="teleporttomap">
			<cannon>teleport to map (map, x, y)</cannon>
			<shortname>teleport to map</shortname>
			<description>An alternative to <ref>usedoor</ref>, teleport to map moves you to a given x,y position on the specified map without the need to create a door-link on the map. Teleport to map does not fade to black. (This command implies a one-tick <ref>wait</ref>)</description>
		</command>
		<command id="dismountvehicle">
			<cannon>dismount vehicle</cannon>
			<shortname>dismount vehicle</shortname>
			<description>Makes you dismount whatever vehicle you are riding. If you are not riding a vehicle, nothing will happen.</description>
		</command>
		<command id="heroiswalking">
			<cannon>hero is walking (who)</cannon>
			<shortname>hero is walking</shortname>
			<description>Returns <ref>true</ref> if the specified hero (by position in the caterpillar) is currently walking. Returns <ref>false</ref> if the hero is standing still.</description>
		</command>
		<command id="puthero">
			<cannon>put hero (who, x, y)</cannon>
			<shortname>put hero</shortname>